<template>
  <v-navigation-drawer
    v-model="$store.state.isNavVisible"
    absolute
    bottom
    temporary
  >
    <v-list
      nav
      dense
    >
      <v-list-item-group>
        <v-list-item
          @click="account"
        >
          <v-list-item-icon>
            <v-icon>
              mdi-account-circle
            </v-icon>
          </v-list-item-icon>
          <v-list-item-action-text>
            {{$t('ACCOUNT')}}
          </v-list-item-action-text>
        </v-list-item>
        <v-list-item
          @click="news"
        >
          <v-list-item-icon>
            <v-icon>
              mdi-newspaper-variant
            </v-icon>
          </v-list-item-icon>
          <v-list-item-action-text>
            {{$t('NEWS')}}
          </v-list-item-action-text>
        </v-list-item>
      </v-list-item-group>
    </v-list>
  </v-navigation-drawer>
</template>

<script src="./Nav.ts"></script>
<style src="./Nav.scss" lang="scss"></style>
